// options.js

export const provinceOptions = [
    "Abra",
    "Agusan del Norte",
    "Agusan del Sur",
    "Aklan",
    "Albay",
    "Antique",
    "Apayao",
    "Aurora",
    "Basilan",
    "Bataan",
    "Batanes",
    "Batangas",
    "Benguet",
    "Biliran",
    "Bohol",
    "Bukidnon",
    "Bulacan",
    "Cagayan",
    "Camarines Norte",
    "Camarines Sur",
    "Camiguin",
    "Capiz",
    "Catanduanes",
    "Cavite",
    "Cebu",
    "Cotabato",
    "Davao de Oro (Compostela Valley)",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Dinagat Islands",
    "Eastern Samar",
    "Guimaras",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Sur",
    "Iloilo",
    "Isabela",
    "Kalinga",
    "La Union",
    "Laguna",
    "Lanao del Norte",
    "Lanao del Sur",
    "Leyte",
    "Maguindanao del Norte",
    "Maguindanao del Sur",
    "Marinduque",
    "Masbate",
    "Misamis Occidental",
    "Misamis Oriental",
    "Mountain Province",
    "Negros Occidental",
    "Negros Oriental",
    "Northern Samar",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Pampanga",
    "Pangasinan",
    "Quezon",
    "Quirino",
    "Rizal",
    "Romblon",
    "Samar",
    "Sarangani",
    "Siquijor",
    "Sorsogon",
    "South Cotabato",
    "Southern Leyte",
    "Sultan Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Tarlac",
    "Tawi-Tawi",
    "Zambales",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay"
  ].sort();
  
  export const municipalityOptions = [
    "Cabusao",
    "Del Gallego",
    "Lupi",
    "Ragay",
    "Sipocot",
    "Gainza",
    "Libmanan",
    "Milaor",
    "Minalabac",
    "Pamplona",
    "Pasacao",
    "San Fernando",
    "Bombon",
    "Calabanga",
    "Camaligan",
    "Canaman",
    "Magarao",
    "Ocampo",
    "Pili",
    "Caramoan",
    "Garchitorena",
    "Goa",
    "Lagonoy",
    "Presentacion",
    "Sagnay",
    "San Jose",
    "Siruma",
    "Tigaon",
    "Tinambac",
    "Baao",
    "Balatan",
    "Bato",
    "Buhi",
    "Bula",
    "Nabua",
    "Naga City"
  ].sort();
  
  export const barangayOptions = [
    "Agaas",
    "Antolon",
    "Bacgong",
    "Bahay",
    "Bikal",
    "Binanuahan",
    "Cabacongan",
    "Cadong",
    "Colongcogong",
    "Canatuan",
    "Caputatan",
    "Gogon",
    "Daraga",
    "Gata",
    "Gibgos",
    "Guijalo",
    "Hanopol",
    "Hanoy",
    "Haponan",
    "Ilawod",
    "Ili-Centro",
    "Lidong",
    "Lubas",
    "Malabog",
    "Maligaya",
    "Mampirao",
    "Mandiclum",
    "Maqueda",
    "Minalaba",
    "Oring",
    "Oroc-Osoc",
    "Pagolinan",
    "Pandanan",
    "Paniman",
    "Patag-Belen",
    "Pili-Centro",
    "Pili-Tabiguian",
    "Poloan",
    "Salvacion",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Solnopan",
    "Tabgon",
    "Tabiguian",
    "Tabog",
    "Tawog",
    "Toboan",
    "Terogo"
  ].sort();
  